POST http://localhost:3000/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjp0cnVlLCJpYXQiOjE3MjEyNTA2ODUsImV4cCI6MTcyMTMwNDY4NX0.uAM-o6qCJOSyjYLETMer8OvoxID3yu9MHaPRGqmIIaY

{
    "name": "newAdmin",
    "password": "sirli",
    "confirm_password": "sirli",
    "phone": "+998901006707"
}

###
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
    "name": "admin",
    "password": "secret"
    
}
###

POST http://localhost:3000/api/admin/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjpmYWxzZSwiaWF0IjoxNzIxMjUwMjgzLCJleHAiOjE3MjEzMDQyODN9.CSUJmkB00PmRpoF2mZcB-kDpuJ_A2zlGP3OLU6HB5RM